### ISSUE TITLE
Hide review projects from home page

### ISSUE THREAD

**Issue by alebastr** [FrostyX/fedora-review-service#10]
I've just opened the [copr home page](https://copr.fedorainfracloud.org/coprs/) and more than a half of the projects listed are created by fedora-review.
I don't think these are of much interest to a regular user who checks the list of projects for something interesting. Have you considered creating the projects with `unlisted_on_hp=True`?

**Comment by FrostyX** [comment]
Oh good catch, thank you very much @alebastr,
I am going to switch to `unlisted_on_hp=True`

**Comment by FrostyX** [comment]
Fixed. I also unlisted all the already existing projects.

```python
from copr.v3 import Client

client = Client.create_from_config_file()
projects = client.project_proxy.get_list("@fedora-review")
projects += client.project_proxy.get_list("frostyx")
for project in projects:
    if project.unlisted_on_hp:
        continue

    if not project.name.startswith("fedora-review-"):
        continue

    print("Unlisting from homepage: {0}".format(project.full_name))
    client.project_proxy.edit(project.ownername, project.name,
                              unlisted_on_hp=True)
```
