### ISSUE TITLE
Manually trigger new Copr build and comment

### ISSUE THREAD

**Issue by FrostyX** [FrostyX/fedora-review-service#11]
Sometimes a build is not triggered, or the contributor edits a previous comment instead of adding a new one, etc, and we might need to manually rebuild the package and generate a new comment.

In Copr we did so if we found a `[copr-build]` string in the comment but I don't want to do this in Bugzilla.

**Comment by michal-josef-spacek** [comment]
I have this situation in the review of perl-Alien-Brotli (https://bugzilla.redhat.com/show_bug.cgi?id=2161558), where the service does review, but the spec file was changed after review.

Could I do a review somehow again by service?

**Comment by FrostyX** [comment]
I am sorry, it's not possible at this moment. 
A Copr build is submitted only if the author of the RHBZ ticket adds a comment with `Spec URL:` and `SRPM URL:`.

But we really need a way to trigger the build some other way. Do you have any ideas? What would be your preferred way?

**Comment by michal-josef-spacek** [comment]
First, I need to understand this tooling myself. :-)

So I could add to the ticket in Bugzilla:
```
For update review in COPR:
Spec URL: https://psalaba.fedorapeople.org/perl-Alien-Brotli/perl-Alien-Brotli.spec
SRPM URL: https://psalaba.fedorapeople.org/perl-Alien-Brotli/perl-Alien-Brotli-0.2.2-2.fc38.src.rpm
```
And this will trigger the COPR build.
Am I saying it right?
