### ISSUE TITLE
Verify URL correctness, use rpmlint on spec

### ISSUE THREAD

**Issue by pemensik** [FrostyX/fedora-review-service#12]
Just opened [review bug #2151289](https://bugzilla.redhat.com/show_bug.cgi?id=2151289) and found those URLs do not point to correct documents.

It would be nice if the service could check at least HTTP headers for given URLs and ensure they are not text/html or similar.

This bug was done by not sponsored user. I think the service should take that into account and do not publish any builds for unsponsored people automatically. But it should make sure those URLs work and spec passes at least rpmlint. Quick feedback doing at least basic check about review is vital I believe. At least rpmlint should be safe for everyone and errors in it should be reported right away to the user.

Full build should be done only for already sponsored people or manual trigger done by human reviewer. That should prevent redistribution of forbidden software from servers of Fedora, including COPR. In the other case both should add [FE-NEEDSPONSOR](https://bugzilla.redhat.com/show_bug.cgi?id=177841) to Blocks field.

**Comment by FrostyX** [comment]
> It would be nice if the service could check at least HTTP headers for given URLs and ensure they are not text/html or similar.

I want this as well. It will allow us to send a tailored for this specific error.

> This bug was done by not sponsored user. I think the service should take that into account and do not publish any builds for unsponsored people automatically. 

To not accidentally build forbidden software, or do you see any other reasons? 
I would really like to keep doing full builds for everybody. I agree that we need to do something about the forbidden software though.

>  But it should make sure those URLs work and spec passes at least rpmlint. 

I would like to avoid running any commands directly on the fedora-review-service instance because then security becomes an issue. Running `rpmlint` should be probably fine but even so, I would like fedora-review-service to process the Fedora Messaging messages as fast as possible and leave all the heavy lifting for Copr.

**Comment by pemensik** [comment]
> To not accidentally build forbidden software, or do you see any other reasons? I would really like to keep doing full builds for everybody. I agree that we need to do something about the forbidden software though.

The main point why people need to use external URLs instead of attaching archives as attachments is to avoid responsibility for redistributing software without permissible license. The reviewer should check that we are even allowed to redistribute it on any of our infrastructure. For people with signed CLA and properly sponsored in Fedora, the chance of submitting disallowed content is minimal. But I think we should be more cautious with new people without known history.

I think we can extract some thing from content they provide to us, but we should not redistribute any content they submit without human review. I think we can make COPR builds, but they should be hidden until some person approves them. It would be more simple to delay building the content until trusted user acked the content to be okay.
> 
> 
> I would like to avoid running any commands directly on the fedora-review-service instance because then security becomes an issue. Running `rpmlint` should be probably fine but even so, I would like fedora-review-service to process the Fedora Messaging messages as fast as possible and leave all the heavy lifting for Copr.

Yes, it is important to do checks on isolated environment, which cannot be misused to run untrusted code and reaching out with results. I am not sure how busy reviews are and never measured it. But what I proposed should be very quick checks. Well except URL fetching, that may take some time depending on used URLs. I admit spawning some worker processing one bug should be preferred.

**Comment by FrostyX** [comment]
> It would be nice if the service could check at least HTTP headers for given URLs and ensure they are not text/html or similar.

We are now complaining with errors like this:

```
There seems to be some problem with the following file.
SRPM URL: https://frosyx.fedorapeople.org/light-1.2.2-9.fc38.src.rpm
Fetching it results in a 403 Forbidden error.
Please make sure the URL is correct and publicly available.


---
This comment was created by the fedora-review-service
https://github.com/FrostyX/fedora-review-service

If you want to trigger a new Copr build, add a comment containing new
Spec and SRPM URLs or [fedora-review-service-build] string.
```
