### ISSUE TITLE
Add Triaged keyword to bug on build pass

### ISSUE THREAD

**Issue by pemensik** [FrostyX/fedora-review-service#13]
It would be nice to mark somehow successful review build. I think keyword ``Triaged`` is exactly for that purpose. If it built, then some simplified way should allow queries for similar builds. Or even use ``AutomationTriaged`` keyword, which is there as well.

**Comment by FrostyX** [comment]
Ah, that's cool. I didn't use keywords in Bugzilla before. If I understand this correctly, it will allow us to create a search of builds that are `Component: Package Review && Keyword: AutomationTriaged` and therefore prioritize the review tickets that can be done quickly?

For the record, the list of keywords is here:
https://bugzilla.redhat.com/describekeywords.cgi

**Comment by FrostyX** [comment]
Thinking about this again, 

> on build pass

This wouldn't be correct. The build passed even if the `fedora-review` finds some issues. From a Copr project settings

> [ ] Run fedora-review tool for packages in this project
> When submitting new package to Fedora, it needs to comply with Fedora Packaging Guidelines. Use fedora-review tool to help you discover packaging errors. Failing fedora-review will not fail the build itself.

We should probably wait until https://pagure.io/FedoraReview/pull-request/463 gets merged and then add the `AutomationTriaged` keyword if count zero errors in the JSON file.

**Comment by FrostyX** [comment]
All the blockers were finished, and #30 was implemented. This is now my most priority RFE and should be quite easy to do.

**Comment by FrostyX** [comment]
This is finished now, I will continue with #6

**Comment by FrostyX** [comment]
Also, the `AutomationTriaged` will only appear for new tickets. I am planning to run the Fedora Review Service on all already existing tickets so that we get the keyword everywhere we can.
