### ISSUE TITLE
Set URL on bug to point to upstream

### ISSUE THREAD

**Issue by pemensik** [FrostyX/fedora-review-service#14]
I think basic processing of Spec file might update URL field of bug to point to URL specified inside spec. It would make it easier to click to information about upstream. Because reviewer should check whether last release is packaged, this is always used.

Of course in case URL field already has any content, then the service should not modify it and let reporter maintain it.

**Comment by FrostyX** [comment]
Thank you @pemensik,
that's a good idea. I don't know how other reviewers but I am opening the upstream homepage many times during the review, it always gets lost and I search for it again and again in the spec file. Having it visible at multiple places won't hurt anything.
