### ISSUE TITLE
Provide information how to get sponsored

### ISSUE THREAD

**Issue by FrostyX** [FrostyX/fedora-review-service#18]
An action should be triggered when a ticket receives the `fedora-review+` flag. If it was given by a packager who is not a sponsor himself, and no other sponsor is currently assigned to the bug, we should post a comment to the ticket. For example:

```
Since this would be your first Fedora package, you will need to get
sponsored into the `packager' group before this package can be
accepted.

It will be a sponsor's responsibility to guide you through the processes that
you will do, and the tools that you will need as a package maintainer. A sponsor
will also be there to answer your packaging-related questions, or to
help you find somebody who knows the answers.

To find yourself a sponsor, please follow these instructions:
https://docs.fedoraproject.org/en-US/package-maintainers/How_to_Get_Sponsored_into_the_Packager_Group/#how_to_find_a_sponsor
```

(A quick draft, it'll be improved when implementing this feature)

**Edit:** Or we can create an issue in the https://pagure.io/packager-sponsors/issues tracker automatically, and then just let the contributor know about it.

**Comment by sanjayankur31** [comment]
Additional note: we also need to update the package maintainer docs to note this when it has been implemented

- https://docs.fedoraproject.org/en-US/package-maintainers/Joining_the_Package_Maintainers/
- https://docs.fedoraproject.org/en-US/package-maintainers/How_to_Get_Sponsored_into_the_Packager_Group/#how_to_find_a_sponsor

are two pages I can think of off the top of my head.

Thanks again for this, it's a great idea!

**Comment by FrostyX** [comment]
I just pushed cdd6f4d which fixes this issue and deployed it to production. A few notes:

- I was able to implement the variant which automatically creates a packager-sponsors ticket, so no manual action from the contributor is needed
- First, a packager-sponsor ticket is created, its information is targeted for sponsors. Then a comment is added to this issue, tagging the contributor by their FAS username. Sponsors don't care about this comment.  Then a comment is added to the Bugzilla ticket, linking the packager-sponsor ticket
- Please, if you find some of the texts confusing, too verbose, etc, let me know
- It is non-trivial to find a FAS username for a given Bugzilla account:
    - We have to parse the `Fedora Account System Username:` line from the first Bugzilla comment which is unreliable
    - We have no way of figuring out if `fedora-review+` was given by a sponsor or not. The packager-sponsor ticket is created in both cases. Sponsors will have to assign the ticket to themselves.
- I will move the docs update suggested by @sanjayankur31 to a separate issue
- @gotmax23 has a valid point but I haven't implemented any opt-out yet. Let's give it some time and see if it's really needed or not
