### ISSUE TITLE
Fedora Review Service wasn't triggered for RHBZ 2263696

### ISSUE THREAD

**Issue by gotmax23** [FrostyX/fedora-review-service#37]
The service didn't trigger for https://bugzilla.redhat.com/show_bug.cgi?id=2263696. Is there something wrong with the ticket formatting? Is there a way I can re-trigger it?

**Comment by gotmax23** [comment]
Hmm, is the issue that `Fedora Account System Username` is not specified in the issue?

https://github.com/FrostyX/fedora-review-service/blob/80de3b1584287920c55879e5bfadad49fc6e6ca4/fedora_review_service/consumer.py#L191-L194

**Comment by FrostyX** [comment]
Hello @gotmax23, thank you for the report.

> Is there a way I can re-trigger it?

You tried to do it correctly using `[fedora-review-service-build]`

> Is there something wrong with the ticket formatting?

The formatting looks good to me. There is a re-occurring issue with Bugzilla not sending messages to fedora-messaging which seems to have happened again. The Fedora Infra team needs to _poke it_ so it starts working again. Once they do it, the Fedora Review Service builds for your ticket should be automatically triggered.

**Comment by FrostyX** [comment]
Nirik poked it, so it works again.
And the Fedora Review Service was successfully triggered for your ticket now :-)

**Comment by gotmax23** [comment]
Thanks for the help @FrostyX!
