### ISSUE TITLE
Truncating package name in sponsor ticket

### ISSUE THREAD

**Issue by berrange** [FrostyX/fedora-review-service#38]
Look at these sponsor tickets:

https://pagure.io/packager-sponsors/issue/610
https://pagure.io/packager-sponsors/issue/628

The first says `Package: kupper-router - ...` when the package name is actually `skupper-router`

The second says `Package: ditorconfig-emacs - ...` when the package name is actually `editorconfig-emacs`.

The first letter of the package name is going missing, but this does not seem to affect all tickets the same. eg:

https://pagure.io/packager-sponsors/issue/626

came through fine, while eg:

https://pagure.io/packager-sponsors/issue/624

seems to have stripped much more than just the first letter - the whole "qt6-qt" prefix is gone.

**Comment by FrostyX** [comment]
Thank you for the report @berrange, and for the provided examples. This shouldn't be hard to fix, I will take a look as soon as I can.
