### ISSUE TITLE
Enhance the handling of broken Source URLs

### ISSUE THREAD

**Issue by carlosrodfern** [FrostyX/fedora-review-service#39]
When the Source URL breaks but the tar ball is still in the srpm, the review.txt appears as blank, failing to handle the scenario gracefully.

Here is an example: 

https://copr.fedorainfracloud.org/coprs/g/fedora-review/fedora-review-2262694-materialx/build/7035565/

**Comment by carlosrodfern** [comment]
It looks like the problem is not related with the Source URL.

In this example, https://copr.fedorainfracloud.org/coprs/g/fedora-review/fedora-review-2262694-materialx/build/7035959/
the Source URL is correct, however, it is blank for fedora 40 and rawhide, but not for 38 or 39.

**Comment by carlosrodfern** [comment]
It appears that this issue is, in fact, a duplicate of this one: https://github.com/fedora-copr/copr/issues/3147

**Comment by FrostyX** [comment]
Ok, let me close the ticket then.

We are also tracking the issue on the fedora-review side
https://pagure.io/FedoraReview/issue/510
